upstream django {
    server web:8000;
}

server {
    listen 80;
    server_name localhost;

    # 1. إعداد الملفات الثابتة (Static Files)
    # Nginx سيقرأها مباشرة من المجلد المشترك بين الحاويات
    location /static/ {
        alias /app/productionfiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # 2. تمرير باقي الطلبات لتطبيق Django
    location / {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}