# Generated by Django 6.0.5 on 2026-05-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketresearchcompany',
            name='code',
            field=models.CharField(default='CXFY0000', max_length=50, unique=True, verbose_name='Company Code'),
            preserve_default=False,
        ),
    ]
