# Generated by Django 6.0.5 on 2026-05-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_marketresearchcompany_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_allowed_to_login',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='marketresearchcompany',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active Contract?'),
        ),
    ]
