# Generated by Django 6.0.5 on 2026-05-22 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_marketresearchcompany_code'),
        ('codeFrame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeframe_analysisjob',
            name='project_name',
        ),
        migrations.AddField(
            model_name='codeframe_analysisjob',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='company_analysis_jobs', to='accounts.marketresearchcompany'),
            preserve_default=False,
        ),
    ]
