# Generated by Django 6.0.5 on 2026-05-28 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_is_allowed_to_login_userprofile_is_active_and_more'),
        ('codeFrame', '0002_remove_codeframe_analysisjob_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeframe_analysisjob',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_analysis_jobs', to='accounts.marketresearchcompany'),
        ),
        migrations.CreateModel(
            name='CodeFrame_CompanyUsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_records', models.IntegerField(default=0)),
                ('used_records', models.IntegerField(default=0)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_quota', to='accounts.marketresearchcompany')),
            ],
        ),
    ]
