# Generated by Django 6.0.5 on 2026-05-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeFrame', '0003_alter_codeframe_analysisjob_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeframe_companyusagequota',
            old_name='allowed_records',
            new_name='allowed_responses',
        ),
        migrations.RenameField(
            model_name='codeframe_companyusagequota',
            old_name='used_records',
            new_name='used_responses',
        ),
    ]
