# Generated by Django 6.0.5 on 2026-05-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeFrame', '0004_rename_allowed_records_codeframe_companyusagequota_allowed_responses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeframe_analysisresult',
            name='extracted_codes_count',
            field=models.IntegerField(default=0, verbose_name='All codes extracted by the AI'),
        ),
        migrations.AddField(
            model_name='codeframe_analysisresult',
            name='processed_responses',
            field=models.IntegerField(default=0, verbose_name='All responses that were processed by the AI'),
        ),
        migrations.AddField(
            model_name='codeframe_analysisresult',
            name='total_records',
            field=models.IntegerField(default=0, verbose_name='All records in the dataset'),
        ),
    ]
